repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: https://github.com/delamatrelya/pre-commit-php
    rev: v0.5.1
    hooks:
      - id: php-cs-fixer
        args: [--config=.php_cs.dist]
      - id: phpstan
        args: [--no-progress]
      - id: psalm
        args: [--no-cache]
      - id: phpunit
        args: [--colors]

additional_dependencies:
  - phpunit/phpunit:^9.0
  - phpstan/phpstan:^0.12
  - vimeo/psalm:^4.3
  - friendsofphp/php-cs-fixer:^3.0

exclude: '^vendor/|^storage/'
